### ISSUE TITLE
Invalid indexing in textgrid import

### ISSUE THREAD

**Issue by MartinKl** [korpling/annatto#329]
https://github.com/korpling/annatto/blob/6e94ce766585c0de9a6c7a4cb068af70b9cbf857/src/importer/textgrid.rs#L466

There are cases in which the index is out of bounds. An example file is attached, import defined as follows:

```toml
[[import]]
format = "textgrid"
path = "..."

[import.config]
skip_audio = true

[import.config.tier_groups]
"ORT-MAU" = ["IP", "KAN-MAU", "MAU", "norm", "lemma", "pos_lang", "pos"] 
```
Panics for: [example.zip](https://github.com/user-attachments/files/17999355/example.zip)
