### ISSUE TITLE
Allow to generate/show workflow section with all properties and their default values

### ISSUE THREAD

**Issue by thomaskrause** [korpling/annatto#331]
It should be possible for the users to see a full example configuration for a module with its standard values. Some modules have manually created examples in their description, but this could be automated. 
The *Configuration* section of the `info` command is already quite large for some modules, so maybe instead of adding it to `info`, this could be a  different sub-command.

**Comment by MartinKl** [comment]
As of #393 modules can be serialized.

I suggest we enforce modules to implement a `Sample` trait providing two functions, one with the default configuration (can simply wrap `default` in cases where the module implements it) and one maximally customized version. The latter might be useful to showcase the use of `Option` fields whose use might require illustration especially for wrapped enums. The default of such fields will always be absence of the key in a default serialization.

This, nevertheless, will (at least in the default setting, not sure it's customizable) show a serialization that might not be idiomatic in the sense of the way we usually illustrate toml configurations. As an example, in our usual examples we show the configuration of annotation components as sth like:

```toml
component = { ctype = "Pointing", layer = "", name = "dep" }
```

The `toml` serializer would provide the following, though:

```toml
[component]
ctype = "Pointing"
layer = ""
name = "dep"
```

This is not a big deal, I guess, but for some modules leads to deeper embedded headed tables rather than inline configurations in is sth to be aware of.

Also, the methods of `Sample` would have to return a `Workflow` struct to ensure the table headings (or keys) are correct. The example above could occur in `collapse` and would have to look the following way to be helpful:

```toml
[[graph_op]]
action = "collapse"

[graph_op.config]
...

[graph_op.config.component]
ctype = "Pointing"
layer = ""
name = "dep"
```

**Comment by MartinKl** [comment]
And just to talk again about inlining, I do believe that a config for collapse is easier to digest for a human reader if the component is inlined as in:

```toml
[[graph_op]]
action = "collapse"

[graph_op.config]
...
component =  { ctype = "Pointing", layer = "", name = "dep" }
```

But of course, I have no evidence of that.
