### ISSUE TITLE
Use consistent syntax in documentation for empty configuration

### ISSUE THREAD

**Issue by thomaskrause** [korpling/annatto#332]
```toml
[import.config]
```
without a body is equivalent to
```toml
[import]
config = {}.
```

While both is supported by TOML, we should stick to one of the variants in the documentation.
