### ISSUE TITLE
`map`: Unify `ns` and `name` in rule definition

### ISSUE THREAD

**Issue by MartinKl** [korpling/annatto#364]
Following the other modules, the annotation qname to be generated by `map` should be provided via a single attribute to deserialize the annotation key. What currently is:

```toml
query = "ud:xpos=/NN/"
target = 1
ns = "ud"
name = "upos"
value = "NOUN"
```

should be something like:

```toml
query = "ud:xpos=/NN/"
target = 1
anno = "ud::upos"
value = "NOUN"
```

Instead of `anno`, also sth like `key` etc could be used. In the long run it's desirable that these attribute names are consistent across all modules and currently `anno` appears to be the most frequently used.
